### ISSUE TITLE
RuntimeError: You need to use the eventlet server. 

### ISSUE THREAD

**Issue by EricJonsson** [EricJonsson/CommunicationPlatform#4]
RuntimeError: You need to use the eventlet server. See the Deployment section of the documentation for more information.

Error on request:
Traceback (most recent call last):
  File "/home/eric/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 319, in run_wsgi
    execute(self.server.app)
  File "/home/eric/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 308, in execute
    application_iter = app(environ, start_response)
  File "/home/eric/.local/lib/python3.8/site-packages/flask/app.py", line 2088, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/eric/.local/lib/python3.8/site-packages/engineio/middleware.py", line 63, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/home/eric/.local/lib/python3.8/site-packages/socketio/server.py", line 589, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/home/eric/.local/lib/python3.8/site-packages/engineio/server.py", line 392, in handle_request
    packets = socket.handle_get_request(
  File "/home/eric/.local/lib/python3.8/site-packages/engineio/socket.py", line 103, in handle_get_request
    return getattr(self, '_upgrade_' + transport)(environ,
  File "/home/eric/.local/lib/python3.8/site-packages/engineio/socket.py", line 158, in _upgrade_websocket
    return ws(environ, start_response)
  File "/home/eric/.local/lib/python3.8/site-packages/engineio/async_drivers/eventlet.py", line 16, in __call__
    raise RuntimeError('You need to use the eventlet server. '

**Comment by durianpuddingupup** [comment]
try [this](https://stackoverflow.com/questions/62309511/runtimeerror-you-need-to-use-the-eventlet-server)? it said uninstall eventlet

**Comment by FilPag** [comment]
It worked! Haha, thanks for the help! :)
