### ISSUE TITLE
ConnectionError on Client

### ISSUE THREAD

**Issue by EricJonsson** [EricJonsson/CommunicationPlatform#7]
Issue when starting client right after player selection. Does not occur consistently and my be related to issue #4. 

Choose player 1 or 2: 2
Traceback (most recent call last):
  File "client.py", line 82, in <module>
    player.ConnectToServer('127.0.0.1', 5000)
  File "client.py", line 51, in ConnectToServer
    self.sio.connect('http://' + ipAddress + ':' + str(port))
  File "/home/eric/.local/lib/python3.8/site-packages/socketio/client.py", line 338, in connect
    raise exceptions.ConnectionError(
socketio.exceptions.ConnectionError: One or more namespaces failed to connect

**Comment by durianpuddingupup** [comment]
you need to `pip install requests`
